# This is a basic workflow to help you get started with Actions

name: build-package.yml

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
    tags:
      - v*
      - Release
      - Pre-Release
      - Build
      - Test

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Get tag names
        id: tag_names
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          commit_message="${{ github.event.head_commit.message }}"
          tag_name=$(echo "$commit_message" | grep -oP '(?<=Release: |Pre-Release: )v?\d+\.\d+\.\d+')
          if [ -z "$tag_name" ]; then
            tag_name=$(echo "$commit_message" | grep -oP '(?<=Update: )v?\d+\.\d+\.\d+')
          fi
          echo "TAG_NAMES=$tag_name" >> $GITHUB_ENV
          
      - name: Check tags
        run: |
          if [[ "${{ env.TAG_NAMES }}" != "Release" && "${{ env.TAG_NAMES }}" != "Pre-Release" ]]; then
            echo "Required tags not found"
            exit 1
          fi
          
      - name: Get project name
        id: project_name
        if: success()
        run: |
          commit_message="${{ github.event.head_commit.message }}"
          project_name=$(echo "$commit_message" | grep -oP '(?<=Release: )[^\s]*')
          if [ -z "$project_name" ]; then
            project_name=$(echo "$commit_message" | grep -oP '(?<=Update: )[^\s]*')
          fi
          echo "PROJECT_NAME=$project_name" >> $GITHUB_ENV
          if [ -z "$project_name" ]; then
            echo "Project name not found"
            exit 1
          fi
          
      # Runs a single command using the runners shell
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          path: classic-coins/
          type: zip
          filename: release.zip
          exclusions: '*.git* /*node_modules/* .editorconfig'

      - name: Upload Artifact
        if: ${{ steps.tag_names.outputs.names[1] == 'Release' || steps.tag_names.outputs.names[1] == 'Pre-Release' }}
        uses: actions/upload-artifact@v2
        with:
          name: release-artifact
          path: release.zip
